name = "Clearlooks Theme"
license = "MIT"
description = "A Linux terminal with the Gtk clearlooks theme."
homepage = "https://github.com/meow464/clearlooks-hugo"
tags = ["clearlooks", "gtk", "terminal"]
features = ["cool af", "pagination"]
min_version = "0.41"

[author]
  name = "Meow464"
  homepage = "https://meow464.neocities.org/"
